### ISSUE TITLE
Results of contribution

### ISSUE THREAD

**Issue by satyam04sharma** [satyam04sharma/CECS-550---Survey-Paper#7]
Key contributions of paper: Description of RLDA/RSLDA and how they work

**Comment by JoeyChor** [comment]
It's still confusing to me, but here's what I got so far:

* Robustness: Sensitivity to outliers and noise (as no data is perfect). If something is robust, it is more resilient to outliers and noise (i.e. accuracy isn't lowered as much if noisy data is put in the dataset).
* L1-norm: Manhattan distance ("snake" distance)
* L2-norm: Euclidean distance (or just distance). Classically used, but performs worse than L1-norm with respect to robustness
* Bhattacharyya error bound:
  * Used to prove robustness.
  * While it is not tight (only the Bayes' error estimation is, as it is the optimal error), Bhattacharyya is easier to calculate.
    * "Since the Bayes classifier is the best classifier that minimizes the probability of classification error [9], minimizing the Bayes error is always expected to lead to good classification models."
    * "Compared to the Bayes error, the Bhattacharyya error [9], [53] that involves the maximization of probabilistic distance measures and probabilistic dependence measures between different classes [52] is a widely used upper bound that provides a close bound to the Bayes error"
* Sparse: Not as in sparse matrices (which would mean it is easier to describe a matrix by its non-zero values than defining each element), but the "number of features is very large and the number of observations is limited" (from [46], L. Clemmensen, T. Hastie, D. Witten, and B. Ersbøll, “Sparse discriminant analysis")
* Instead of getting decomposition vectors from eigendecomposition (which causes the bounded number of features), we should use Alternating Direction Method of Multipliers (rewrite problem into ADMM problem then converting the problem to a convex, simple function)

To do:
* Understand ADMM more (at least enough to give a quick high-level summary)
* Understand the algorithm more (maybe not understand each step in a detailed fashion, but understand the core loop and why)
* Understand how RSLDA's algorithm differs from RLDA's
* Understand "Recursive RLDA for Multiple Discriminant Directions" more (I think I understand high-level, but I don't know the details of how it works).

**Comment by satyam04sharma** [comment]
I dont think understanding in depth is necessary. It looks like an old paper there must be newer methods evolved that give a more robust approach. Lets start pushing topics inside readme.md file.
We have a presentation on this Tuesday I guess.

**Comment by satyam04sharma** [comment]
Closed and presentation added to deck
